//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.28 at 09:19:07 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://example.com/ws/elements", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.we.elements;
